analytics: {}
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.76098
  lightness: 0.297297
  rhythmicContrast: 0.728885
  saturation: 0.440878
cta: {}
layout_spectrum: 0.006757
name: Rojas Film
opengraph: {}
purpose: []
typography_spectrum: 0.505912
